import { create } from "zustand";

const infos = [
    {
        id: 0,
        slug: "/solutions/pfsense",
        title: "Fonctionnalité",
        list: [
            {
                id: 0,
                title: '<strong class="importantCyber">Pare-feu</strong>',
                items: [
                    "<strong class='important'>Inspection</strong> dynamique des <strong class='important'>paquets</strong> (SPI) pour une sécurité renforcée.",
                    "<strong class='important'>Blocage</strong> par <strong class='important'>GeoIP</strong> pour contrôler l'accès en fonction de la localisation.",
                    "<strong class='important'>Anti-Spoofing</strong> pour éviter les falsifications d'adresse IP.",
                    "<strong class='important'>Réseau</strong> invité avec <strong class='important'>portail</strong> captif pour gérer les utilisateurs externes.",
                    "<strong class='important'>Règles</strong> basées sur le <strong class='important'>temps</strong> pour une gestion fine des connexions.",
                    "<strong class='important'>Limites</strong> de connexion pour réguler l'utilisation des ressources.",
                    "<strong class='important'>Mappage</strong> NAT (entrant / sortant) pour une configuration réseau flexible.",
                ],
            },
            {
                id: 1,
                title: '<strong class="importantCyber">Routeur</strong>',
                items: [
                    "<strong class='important'>Routage</strong> basé sur des politiques pour des décisions de trafic avancées.",
                    "<strong class='important'>Support</strong> simultané d'<strong class='important'>IPv4</strong> et d'<strong class='important'>IPv6</strong> pour une transition fluide.",
                    "<strong class='important'>Routage</strong> statique configurable pour une personnalisation maximale.",
                    "<strong class='important'>Traduction</strong> de préfixe de réseau <strong class='important'>IPv6</strong> pour gérer les adresses.",
                    "<strong class='important'>Annonces</strong> de routeur <strong class='important'>IPv6</strong> pour une meilleure connectivité.",
                    "<strong class='important'>Support</strong> d'<strong class='important'>adresses</strong> IP multiples par <strong class='important'>interface</strong>.",
                    "<strong class='important'>Serveur</strong> PPPoE pour la connexion à haut débit.",
                ],
            },
            {
                id: 2,
                title: '<strong class="importantCyber">Prévention des attaques</strong>',
                items: [
                    "<strong class='important'>IDS/IPS</strong> pour une détection et une prévention des intrusions en temps réel.",
                    "<strong class='important'>Analyseur</strong> de paquets basé sur <strong class='important'>Snort</strong> pour une sécurité avancée.",
                    "<strong class='important'>Détection</strong> des applications de la couche 7 pour identifier le trafic spécifique.",
                    "<strong class='important'>Règles</strong>, <strong class='important'>sources</strong> et catégories multiples pour une flexibilité accrue.",
                    "<strong class='important'>Base</strong> de données des menaces <strong class='important'>Emerging Threats</strong> pour rester à jour.",
                    "<strong class='important'>Liste noire</strong> pour bloquer les adresses IP malveillantes.",
                    "<strong class='important'>Profils</strong> de règles prédéfinis pour une configuration rapide.",
                    "<strong class='important'>Configuration</strong> intuitive par interface pour une gestion simplifiée.",
                    "<strong class='important'>Suppression</strong> des faux positifs pour des alertes pertinentes.",
                    "<strong class='important'>Inspection</strong> approfondie des paquets (DPI) pour analyser le contenu du trafic.",
                    "<strong class='important'>Blocage</strong> des applications indésirables pour renforcer la sécurité.",
                ],
            },
            {
                id: 3,
                title: '<strong class="importantCyber">VPN</strong>',
                items: [
                    "<strong class='important'>IPsec</strong> pour une sécurité robuste des connexions.",
                    "<strong class='important'>OpenVPN</strong> pour une flexibilité et une compatibilité maximales.",
                    "<strong class='important'>WireGuard</strong> pour des performances optimisées et une configuration simple.",
                    "<strong class='important'>VPN</strong> site à site et accès à distance pour une connectivité sécurisée.",
                    "<strong class='important'>Cryptage</strong> SSL pour protéger les données en transit.",
                    "<strong class='important'>Client</strong> VPN compatible avec plusieurs systèmes d'exploitation.",
                    "<strong class='important'>L2TP/IPsec</strong> pour une utilisation mobile sécurisée.",
                    "<strong class='important'>Support</strong> d'<strong class='important'>IPv6</strong> pour un avenir durable.",
                    "<strong class='important'>Split-tunneling</strong> pour une gestion optimisée du trafic.",
                    "<strong class='important'>Tunnels</strong> multiples pour des connexions flexibles.",
                    "<strong class='important'>Basculement</strong> de tunnel VPN pour maintenir la connectivité.",
                    "<strong class='important'>Support</strong> NAT pour les configurations réseau complexes.",
                    "<strong class='important'>Routage</strong> automatique ou personnalisé selon les besoins.",
                    "<strong class='important'>Authentification</strong> locale des utilisateurs ou via RADIUS/LDAP pour un accès sécurisé.",
                ],
            },
            {
                id: 4,
                title: '<strong class="importantCyber">Proxy et Filtrage de Contenu</strong>',
                items: [
                    "<strong class='important'>Proxy</strong> HTTP et HTTPS pour contrôler le trafic web.",
                    "<strong class='important'>Proxy</strong> avec mise en cache pour améliorer les performances.",
                    "<strong class='important'>Filtrage</strong> des domaines/URL pour bloquer l'accès à des contenus indésirables.",
                    "<strong class='important'>Filtrage</strong> anti-virus pour protéger les utilisateurs des menaces.",
                    "<strong class='important'>SafeSearch</strong> pour sécuriser les recherches sur Internet.",
                    "<strong class='important'>Filtrage</strong> des URL et du contenu HTTPS pour une sécurité accrue.",
                    "<strong class='important'>Rapports</strong> sur l'accès aux sites Web pour une analyse approfondie.",
                    "<strong class='important'>Liste</strong> noire de noms de domaine (DNSBL) pour bloquer les sites nuisibles.",
                    "<strong class='important'>Rapports</strong> d'utilisation pour surveiller l'activité réseau.",
                ],
            },
            {
                id: 5,
                title: '<strong class="importantCyber">Services & Réseaux</strong>',
                items: [
                    "<strong class='important'>DNS</strong> dynamique pour une gestion simplifiée des adresses.",
                    "<strong class='important'>Serveur</strong> DHCP pour une allocation automatique des adresses IP.",
                    "<strong class='important'>Redirection</strong> DNS pour gérer le trafic efficacement.",
                ],
            },
            {
                id: 6,
                title: '<strong class="importantCyber">Gestion de la Configuration</strong>',
                items: [
                    "<strong class='important'>Configuration</strong> par interface Web pour une gestion facile.",
                    "<strong class='important'>Assistant</strong> d'installation pour simplifier la configuration initiale.",
                    "<strong class='important'>Administration</strong> à distance par interface Web pour plus de flexibilité.",
                    "<strong class='important'>Tableau</strong> de bord personnalisable pour un suivi efficace.",
                    "<strong class='important'>Sauvegarde/restauration</strong> de configuration simple pour une récupération rapide.",
                    "<strong class='important'>Exportation/importation</strong> de la configuration pour faciliter la migration.",
                    "<strong class='important'>Sauvegarde</strong> automatique cryptée vers le cloud <strong class='important'>Netgate</strong> pour une sécurité accrue.",
                    "<strong class='important'>Droits</strong> d'administration de niveau variable pour un contrôle granulaire.",
                    "<strong class='important'>Support</strong> multilingue pour une utilisation globale.",
                    "<strong class='important'>Mises</strong> à jour simples pour maintenir le système à jour.",
                    "<strong class='important'>Configuration</strong> compatible avec les versions précédentes.",
                    "<strong class='important'>Console</strong> série pour un accès au shell et des options de récupération.",
                    "<strong class='important'>Wake-on-LAN</strong> pour gérer les appareils à distance.",
                ],
            },
            {
                id: 7,
                title: '<strong class="importantCyber">Gestion de l\'authentification des utilisateurs</strong>',
                items: [
                    "<strong class='important'>Base</strong> de données locale des utilisateurs et des groupes pour une gestion facile.",
                    "<strong class='important'>Privilèges</strong> basés sur les utilisateurs et les groupes pour un contrôle d'accès sécurisé.",
                    "<strong class='important'>Expiration</strong> automatique des comptes en option pour une meilleure sécurité.",
                    "<strong class='important'>Authentification</strong> RADIUS externe pour une intégration facile.",
                    "<strong class='important'>Verrouillage</strong> automatique après des tentatives répétées pour prévenir les abus.",
                ],
            },
            {
                id: 8,
                title: '<strong class="importantCyber">Gestion de la sécurité système</strong>',
                items: [
                    "<strong class='important'>Protection</strong> de la sécurité de l'interface Web pour éviter les accès non autorisés.",
                    "<strong class='important'>Protection</strong> CSRF pour prévenir les attaques par falsification de requête.",
                    "<strong class='important'>Protection</strong> contre les <strong class='important'>referrer</strong> HTTP pour sécuriser les communications.",
                    "<strong class='important'>Protection</strong> contre le <strong class='important'>rebinding</strong> DNS pour éviter les détournements.",
                    "<strong class='important'>Sécurité</strong> du transport HTTP Strict pour renforcer la sécurité des connexions.",
                    "<strong class='important'>Accès</strong> SSH optionnel basé sur une clé pour une administration sécurisée.",
                ],
            },
            {
                id: 9,
                title: '<strong class="importantCyber">Gestion de la résilience/fiabilité</strong>',
                items: [
                    "<strong class='important'>Clustering</strong> haute disponibilité multi-nœuds en option pour assurer la continuité.",
                    "<strong class='important'>Multi-WAN</strong> pour l'équilibrage de la charge et le basculement.",
                    "<strong class='important'>Reverse Proxy</strong> pour gérer le trafic entrant efficacement.",
                    "<strong class='important'>Basculement</strong> automatique de la connexion pour éviter les interruptions.",
                    "<strong class='important'>Limitation</strong> de la bande passante pour optimiser l'utilisation des ressources.",
                    "<strong class='important'>Assistant</strong> de mise en forme du trafic pour prioriser les applications.",
                    "<strong class='important'>Réserver</strong> ou restreindre la bande passante selon les priorités.",
                    "<strong class='important'>Partage</strong> équitable de la bande passante pour un accès juste.",
                    "<strong class='important'>Quotas</strong> de transfert de données des utilisateurs pour gérer l'utilisation.",
                ],
            },
            {
                id: 10,
                title: '<strong class="importantCyber">Rapports surveillance du Système</strong>',
                items: [
                    "<strong class='important'>Tableau</strong> de bord avec widgets configurables pour une vue personnalisée.",
                    "<strong class='important'>Journalisation</strong> locale pour un suivi des activités.",
                    "<strong class='important'>Enregistrement</strong> à distance pour une gestion centralisée.",
                    "<strong class='important'>Graphiques</strong> de surveillance locale pour visualiser les performances.",
                    "<strong class='important'>Graphiques</strong> de trafic d'interface en temps réel pour une analyse rapide.",
                    "<strong class='important'>Surveillance</strong> SNMP pour une gestion réseau efficace.",
                    "<strong class='important'>Notifications</strong> via l'interface web, SMTP ou Growl pour rester informé.",
                    "<strong class='important'>Surveillance</strong> du matériel pour prévenir les pannes.",
                    "<strong class='important'>Outils</strong> de diagnostic de réseau pour résoudre les problèmes rapidement.",
                ],
            },
        ],
    },
];

const solutionsStore = create((set) => ({
    infos,
}));

export default solutionsStore;
