import "@/styles/globals.scss";
import Header from "@/components/Header";

import Footer from "@/components/Footer";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="fr">
            <body>
                {" "}
                <Header />
                {children} <Footer></Footer>
            </body>
        </html>
    );
}
